name: CI

on:

  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
